---
author_notes:
- 
-
-
-
authors:
- admin 
- Kristian Thorborg
- Per Hölmich
- Kasper Krommes
date: "2020-12-01T00:00:00Z"
doi: ""
featured: false
image:
  caption: 
  focal_point: ""
  preview_only: false
projects: []
publication: 'International Journal of Sports Physical Therapy, 15, 947–957. Doi.org/10.26603/ijspt20200947'
publication_short: ""
publication_types:
- "2"
publishDate: "2020-12-01T00:00:00Z"
slides: 
summary: 
tags:
- Football
- Hamstring
- Sprint Performance
title: "Sprint performance in football (soccer players with and without a previous hamstring strain injury: An explorative cross-sectional study"
url_code: ""
url_dataset: ""
url_pdf: ""
url_poster: ""
url_project: ""
url_slides: ""
url_source: https://pubmed.ncbi.nlm.nih.gov/33344011/
url_video: ""
---

# Abstract  

**Background**  
Hamstring strain injuries are common in many sports. Following a hamstring injury, deficits in peak and explosive strength may persist after return to sport potentially affecting sprint performance. Assessment of repeated-sprint ability is recognized as an important part of the return to sport evaluation after a hamstring injury.Purpose: This purpose of this exploratory cross-sectional study was to compare sprinting performance obtained during a repeated-sprint test between football players with and without a previous hamstring strain injury.  

**Methods**  
Forty-four fully active sub-elite football players, 11 with a previous hamstring strain injury during the preceding 12 months (cases; mean age, SD: 25.6 ± 4.4) and 33 demographically similar controls (mean age, SD: 23.2 ± 3.7), were included from six clubs. All players underwent a repeated-sprint test, consisting of six 30-meter maximal sprints with 90 seconds of recovery between sprints. Sprint performance was captured using high-speed video-recording and subsequently assessed by a blinded tester to calculate maximal sprint velocity, maximal horizontal force, maximal horizontal power, and mechanical effectiveness.  

**Results**  
A significant between-group difference was seen in favor of players having a previous hamstring injury over 6 sprints for maximal velocity (mean difference: 0.457 m/s, 95% CI: 0.059-0.849, p = 0.025) and mechanical effectiveness (mean difference: 0.009, 95% CI: 0.001-0.016, p = 0.020).  

**Conclusion**  
Repeated-sprint performance was not impaired in football players with a previous hamstring strain injury; in fact, higher mean maximal sprinting velocity and better mechanical effectiveness were found in players with compared to without a previous hamstring injury. The higher sprinting velocity, which likely increases biomechanical load on the hamstring muscles, in previously injured players may increase the risk of recurrent injuries.
