---
author_notes:
- 
- 
-
-
-
authors:
- admin 
- Kasper Krommes
- Mathias Nielsen
- Kasper Thornton
- Per Hölmich
- Per Aagaard
- Jacob Penalver
- Kristian Thorborg
date: "2021-04-01T00:00:00Z"
doi: ""
featured: false
image:
  caption: 
  focal_point: ""
  preview_only: false
projects: []
publication: 'International Journal of Sports Physiology and Performance, 1–7. Doi.org/10.1123/ijspp.2020-0713'
publication_short: ""
publication_types:
- "2"
publishDate: "2021-04-01T00:00:00Z"
slides: 
summary: 
tags:
- Football
- Hamstring
- Quadriceps
- Strength profiles
title: "Hamstring and Quadriceps Muscle Strength in Youth to Senior Elite Soccer: A Cross-Sectional Study Including 125 Players"
url_code: ""
url_dataset: ""
url_pdf: ""
url_poster: ""
url_project: ""
url_slides: ""
url_source: https://journals.humankinetics.com/view/journals/ijspp/16/10/article-p1538.xml
url_video: ""
---

# Abstract

**Purpose**  
Increasing age, high quadriceps strength, and low hamstring muscle strength are associated with hamstring strain injury in soccer. The authors investigated the age-related variation in maximal hamstring and quadriceps strength in male elite soccer players from under-13 (U-13) to the senior level.  

**Methods**  
A total of 125 elite soccer players were included from a Danish professional soccer club and associated youth academy (first tier; U-13, n=19; U-14, n=16; U-15, n=19; U-17, n=24; U-19, n=17; and senior, n=30). Maximal voluntary isometric force was assessed for the hamstrings at 15° knee joint angle and for the quadriceps at 60° knee joint angle (0°=full extension) using an external-fixated handheld dynamometer. Hamstring-to-quadriceps strength (H:Q) ratio and hamstring and quadriceps maximal voluntary isometric force levels were compared across age groups (U-13 to senior).  

**Results**  
Senior players showed 18% to 26% lower H:Q ratio compared with all younger age groups (P≤0.026). Specific H:Q ratios (mean [95% confidence interval]) were as follows: senior, 0.45 (0.42–0.48); U-19, 0.61 (0.55–0.66); U-17, 0.56 (0.51–0.60); U-15, 0.59 (0.54–0.64); U-14, 0.54 (0.50–0.59); and U-13, 0.57 (0.51–0.62). Hamstring strength increased from U-13 to U-19 with a significant drop from U-19 to the senior level (P=0.048), whereas quadriceps strength increased gradually from U-13 to senior level.  

**Conclusion**  
Elite senior soccer players demonstrate lower H:Q ratio compared with youth players, which is driven by lower hamstring strength at the senior level compared with the U-19 level combined with a higher quadriceps strength. This discrepancy in hamstring and quadriceps strength capacity may place senior-level players at increased risk of hamstring muscle strain injuries.
