---
author_notes:
- 
- 
-
-
-
authors:
- admin 
- Kristian Thorborg
- Joanne Kemp
- Michael Reiman
- Per Hölmich
date: "2021-05-01T00:00:00Z"
doi: ""
featured: false
image:
  caption: 
  focal_point: ""
  preview_only: false
projects: []
publication: 'Journal of Science and Medicine in Sport. Doi.org/10.1016/j.jsams.2021.05.006'
publication_short: ""
publication_types:
- "2"
publishDate: "2021-05-01T00:00:00Z"
slides: 
summary: 
tags:
- Femoroacetabular Impingement Syndrome
- Rate of force development
- Hip Arthroscopy
title: "Maximal hip muscle strength and rate of torque development 6-30 months after hip arthroscopy for femoroacetabular impingement syndrome: A cross-sectional study"
url_code: ""
url_dataset: ""
url_pdf: ""
url_poster: ""
url_project: ""
url_slides: ""
url_source: https://www.jsams.org/article/S1440-2440(21)00131-6/fulltext
url_video: ""
---

# Abstract

**Objectives**  
Reduced sports function is often observed after hip arthroscopy for femoroacetabular impingement syndrome (FAIS). Impaired muscle strength could be reasons for this. We aimed to investigate hip muscle strength after hip arthroscopy for FAIS and its association with sports function and participation.  

**Design**  
Cross-sectional study.  

**Methods**  
We included 45 patients (34 males; mean age: 30.6 ± 5.9years) after unilateral hip arthroscopy for FAIS (mean follow-up [range]: 19.3 [9.8–28.4] months). Maximal isometric hip muscle strength (Nm/kg) including early- (0–100 ms) and late-phase (0–200 ms) rate of torque development (Nm∗kg−1∗s−1) for adduction, abduction, flexion, and extension was measured with an externally fixated handheld dynamometer and compared between operated and non-operated hip. Associations between muscle strength and self-reported sports function and return to sport were investigated.  

**Results**  
For maximal hip muscle strength, no between-hip differences were observed for adduction, abduction, flexion, and extension (p ≥ 0.102). For rate of torque development, significantly lower values were observed for the operated hip in flexion at both 0–100 ms (mean difference: 1.58 Nm∗kg−1∗s−1, 95% CI [0.39; 2.77], p=0.01) and 0–200 ms (mean difference: 0.72 Nm∗kg−1∗s−1, 95% CI [0.09; 1.35], p=0.027). Higher maximal hip extension strength was significantly associated with greater ability to participate fully in preinjury sport at preinjury level (odds ratio: 17.71 95% CI [1.77; 177.60]).  

**Conclusions**  
After hip arthroscopy for FAIS subjects show limited impairments in maximal and explosive hip muscle strength between operated and non-operated hip. Higher muscle strength was positively associated with higher sports function and ability to participate in sport.
