---
author_notes:
- 
- 
-
-
-
authors:
- Jack Dawkins
- admin 
- Jake Willott
- Lars Andersen
- Kristian Thorborg
date: "2021-01-01T00:00:00Z"
doi: ""
featured: false
image:
  caption: 
  focal_point: ""
  preview_only: false
projects: []
publication: 'Translational Sports Medicine, Doi.org/10.1002/tsm2.238'
publication_short: ""
publication_types:
- "2"
publishDate: "2021-01-01T00:00:00Z"
slides: 
summary: 
tags:
- Football
- Groin
- Copenhagen Adduction
- Strength
title: "Effects of a low-dose Copenhagen Adduction exercise intervention on adduction strength in sub-elite male footballers: a randomised controlled trial"
url_code: ""
url_dataset: ""
url_pdf: ""
url_poster: ""
url_project: ""
url_slides: ""
url_source: https://onlinelibrary.wiley.com/doi/full/10.1002/tsm2.238
url_video: ""
---

# Abstract  

Footballers with weak hip adductors are at increased risk of groin injury, and adductor strengthening has been shown to reduce this risk. However, the minimal effective dose of strength training to improve hip adductor strength and mitigate the risk of adductor problems remains unknown. The aim of this randomised controlled trial was to investigate the training and detraining effects of a low-dose Copenhagen adduction exercise (CA) intervention in sub-elite male footballers on eccentric hip adduction strength (primary outcome) and peak adductor squeeze strength (secondary outcome). Thirty-nine male footballers were randomised into two groups: The intervention group completed the CA twice weekly during six in-season weeks in addition to normal football training, while the control group continued normal football training. Strength testing was performed at weeks 0, 3, 6 (training period), and weeks 7-9 (detraining period). There was no between-group difference in eccentric strength at week 6 and 9. There was a significant group by time interaction at 6 weeks (0.52 Nm/kg, 95% CI 0.17-0.86) and 9 weeks (0.59 Nm/kg, 95% CI 0.25-0.93) at which the intervention group displayed greater adductor squeeze strength. These results suggest the low-dose CA intervention is insufficient to modify eccentric hip adduction strength but improves peak adductor squeeze strength.